Resources:
  S3AdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3FullAccess
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: s3:*
            Resource: '*'
      Groups: ['admin'] 